- name: Deploy GlusterFS cluster
  hosts: gluster
  become: True
  vars_files: 
    - vars.yml
  
  roles:
    - dmonagha.ufw
    - dmonagha.glusterfs
  
  tasks:
    - name: Ensure Gluster brick and mount directories exist.
      file: 
        path: "{{ item }}"
        state: directory 
        mode: 0775
      loop:
          - "{{ gluster_brick_dir }}"
          - "{{ gluster_mount_dir }}"

    - name: Configure Gluster volume.
      gluster_volume:
        state: present
        name: "{{ gluster_brick_name }}"
        brick: "{{ gluster_brick_dir }}"
        replicas: 3
        cluster: 
          - 192.168.10.21
          - 192.168.10.22
          - 192.168.10.23
        host: "{{ inventory_hostname }}"
        force: yes
      run_once: true

    - name: Ensure Gluster volume is mounted.
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted