# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure(2) do |config|

    # Base VM OS configuration
    config.vm.box = "ubuntu/trusty64"
    config.vm.synced_folder '.', '/vagrant', disabled: true
    # Use the same key for each machine
    config.ssh.insert_key = false
    config.vbguest.auto_update = false

    # Customize hardware for each VM.
    config.vm.provider "virtualbox" do |vb|  
     vb.memory = "1024"
    end
    
    # Provision each of the VMs for the GlusterFS cluster.
    N = 3
    (1..N).each do |machine_id|
      config.vm.define "gfsn#{machine_id}" do |machine|
      machine.vm.hostname = "gfsn#{machine_id}"
      machine.vm.network "private_network", ip: "192.168.10.#{20+machine_id}"
    
       # Only execute once the Ansible provisioner
       # when all the machines are up and ready.
       if machine_id == N
        machine.vm.provision :ansible do |ansible|
          # Disable default limit to connect to all the machines.
          ansible.limit = "all"
          # Set inventory and playbook location.
          ansible.inventory_path = "hosts"
          ansible.playbook = "gluster-cluster.yml"
        end
    end
  end
end

end